[sources.startup]
type = "startup"

[handlers.discord-dm]
type = "discord-dm"
user-id = "${DISCORD_USER_ID}"
bot-token = "${DISCORD_TOKEN}"

[[triggers]]
source = "startup"
emit = "startup-trigger"

[[actions]]
handler = "discord-dm"
event = "startup-trigger"
emit = "discord-hello"
arguments.message = "Ancymon says hello!"
